### ISSUE TITLE
Theme-Options > Error: Request failed with status code 400 / Unable to compile the theme

### ISSUE THREAD

**Issue by niklas-himself** [digitalmanufaktur/shopware6-manu-theme#10]
Unable to compile the theme "DmfManuTheme". Undefined variable $dmf-product-box-image-background-color: /html/shopware/custom/plugins/shopware6-manu-theme-master/src/Resources/app/storefront/src/scss/component/product-box.scss on line 31, at column 9

**Comment by Niklasliedtke** [comment]
Hi, thanks for the issue. We will have a look at this and might integrate a solution in the next release.

**Comment by chrin261295** [comment]
Hey, thanks for the reply. Just found out that this error occurs when I want to save the settings with an empty border-field in the footer.
