### ISSUE TITLE
Cross-sell products not showing 

### ISSUE THREAD

**Issue by qx54** [digitalmanufaktur/shopware6-manu-theme#11]
The cross-sell products are not being displayed on the product page by default. Only after explicitly assigning the default product page layout in the product settings it works.

It looks like the default product page layout is not correctly being applied without assigning it.

PS: This issue has already resulted in three negative reviews in the Shopware store, which is a pity for such a great theme.

**Comment by AERONIKHD** [comment]
Hello,
is there already a solution for this problem?

**Comment by Niklasliedtke** [comment]
Hi there,
currently it is not planned to change this logic. We are pretty sure that products without a page layout is a feature that will be removed in a future shopware version.
