### ISSUE TITLE
Inkompatibilität mit Shopware v 6.4

### ISSUE THREAD

**Issue by OlliZabal** [digitalmanufaktur/shopware6-manu-theme#2]
Hallo,
stimmt es, dass das Theme aktuell mit Shopware v 6.4 inkompatibel ist?
Gruß

**Comment by LiaraAlis** [comment]
Ich fürchte ja, es hat sich einiges geändert, was hier erstmal angepasst werden müsste.

**Comment by OlliZabal** [comment]
Habe inzwischen einen Compare gefahren und die Anpassungen soweit übertragen (Tests noch offen). So viele sind es zum Glück nicht!
Die price-unit.html.twig im Bereich {% block component_product_box_price %} hat die meisten Anpassungen erfahren.
Hier stellt sich mir die Frage, ob man das nun so nicht via {{ parent() }} ggf. komplett übernehmen kann.

**Comment by LiaraAlis** [comment]
So wie ich das bislang beurteilen kann, sind die Änderungen vor allem, dass `shopware.theme` nun mit `theme_config()` ersetzt werden muss und dass in dem ein oder anderem Template ein paar Blöcke entfernt wurden.
Ich hoffe, dass es ein Update für das Theme im Store gibt. Eventuell können wir ja auch mit einem PR aushelfen? ;)

**Comment by OlliZabal** [comment]
Ja das stimmt - das mit `shopware.config.core.` zu `config('core.` hatte ich nicht erwähnt, weil überschaubar.

**Comment by Niklasliedtke** [comment]
Hallo zusammen, 

vielen Dank für eure Anfragen! Die Kompabilität des Themes mit Shopware 6.4 ist bereits in Arbeit, aufgrund der diversen Änderungen und neuen Features (wie dem Merkzettel), die wir im Theme natürlich integrieren möchten, noch nicht hergestellt.

Perspektivisch werden wir das Update spätestens in der kommenden Woche hier und im Shopware Store veröffentlichen.

Viele Grüße
Niklas Liedtke
digital.manufaktur GmbH

**Comment by LiaraAlis** [comment]
@Niklasliedtke Hallo Niklas,

sehr cool – vielen Dank für die Rückmeldung!
Da freue ich mich sehr drauf. :)

Viele Grüße,
Alexander Pankow

**Comment by amenk** [comment]
https://github.com/digitalmanufaktur/shopware6-manu-theme/tree/v2.0.0 :partying_face:

**Comment by amenk** [comment]
@OlliZabal  close ?
