### ISSUE TITLE
Plugin in store does not match Github Version 2.0.2

### ISSUE THREAD

**Issue by acydburn** [digitalmanufaktur/shopware6-manu-theme#3]
Hi Guys (and Gals),

it seems the store version is not the same as the version here. If i download from the Shopware store the listing template file for example is still the old one.

If you use the github repo everything is OK - but the plugin from the store just does not work for 6.4. :/

Best,
Meik

**Comment by amenk** [comment]
How are you trying to install it? Not with Composer / friendsofshopware repo, right? Are you already on Shopware 6.4.1.0 ?

**Comment by acydburn** [comment]
With composer (Friendsofshopware Repo), yes. Shopware 6.4.1.0... but i then also downloaded the ZIP directly from the Shopware Account and saw the files were outdated.

So i assume the zip uploaded to the store itself might be incomplete

**Comment by Niklasliedtke** [comment]
Hi @acydburn  ; we updated the ZIP-Repository in the Shopware Store to make sure it matches the GitHub Version. Please have a look, if it works for you now.

**Comment by acydburn** [comment]
Hi Niklas, 

It's better in the sense that the store now returns the 2.0.1 ZIP - this is what i think judging from the changelog contents which does not include the 2.0.2 changelog entry. 

For me the issue is resolved - but maybe upload a clean 2.0.3? This way those using composer get the updated zip too.

Many thanks anyways - best regards,
Meik
