### ISSUE TITLE
Store-Version Kompatibilität Shopware Versionen > 6.4.1.0

### ISSUE THREAD

**Issue by LiaraAlis** [digitalmanufaktur/shopware6-manu-theme#4]
Laut Store-Eintrag ist das Theme nur kompatibel bis 6.4.1.0.
Soweit ich das überblicken kann, müsste das Theme doch auch problemlos mit den Versionen 6.4.1.1, 6.4.1.2 sowie den Versionen 6.4.2.x kompatibel sein oder habe ich etwas übersehen?
Wäre super, wenn die Kompatibilität im Store angepasst werden würde. Die `composer.json` ist ja bereits korrekt.

**Comment by amenk** [comment]
@LiaraAlis hast du es bereits mit einer neuren Version getestet? vielleicht sogar 6.4.3.x ?

**Comment by LiaraAlis** [comment]
@amenk Bisher noch nicht. Noch nicht die Zeit zu gefunden.

**Comment by amenk** [comment]
@proj-dmf Danke für das neue [Release](https://github.com/digitalmanufaktur/shopware6-manu-theme/releases/tag/v2.0.3). Das Theme scheint auf den ersten Blick nach einem ersten Test bei uns auch mit 6.4.3.0 zu funktionieren.

**Comment by amenk** [comment]
Sorry, habe mich vertan. Wir haben auch erst mit 6.4.2.1 getestet.
@proj-dmf Wie sind die Pläne für 6.4.3.0 ?

**Comment by Niklasliedtke** [comment]
Hi @amenk, die Version 2.0.3 des Themes ist auch mit Shopware 6.4.3.0 kompatibel.
