### ISSUE TITLE
JS error in console

### ISSUE THREAD

**Issue by OlliZabal** [digitalmanufaktur/shopware6-manu-theme#5]
Hi there, just noticed an JS error in the consolte `this._sortBtn is null`.

**Comment by amenk** [comment]
@OlliZabal  auf welcher Seite tritt das auf? Mit welchen Versionen (Shopware, Theme) ? Wir scheinen den JS Fehler nicht nachstellen zu können.

**Comment by OlliZabal** [comment]
@amenk

- Shopware v6.4.3.1 Stable Version
- Manu Theme v 2.0.3

Der Fehler tritt auf einer Blog-Listingseite (Plugin "NetzpBlog6") auf, auf der wohl die SW-Filterfunktion (Blog-Kategorien) genutzt wird.
