### ISSUE TITLE
[Entwicklerfrage] Config Variable wishlist-position hat andere Translation

### ISSUE THREAD

**Issue by amenk** [digitalmanufaktur/shopware6-manu-theme#6]
Uns ist aufgefallen, dass die Config

https://github.com/digitalmanufaktur/shopware6-manu-theme/blob/e87f2b5cae57c0c1bba5b52eb473dae8c3606da2/src/Resources/theme.json#L2303

"dmf-product-box-wishlist-position"

den Text "position der überschrift hat". Eigentlich scheint es hier um die Wishlist zu gehen.

Ist das eine Altlast oder hat sich da ein Fehler eingeschlichen?

**Comment by Niklasliedtke** [comment]
Hallo @amenk , danke für den Issue. Wir werden dies prüfen und bei Bedarf im kommenden Release berücksichtigen.
